### PR TITLE
Remove support for php 5.3 and 7.0

### PR DESCRIPTION
**Pull request by ramereth**
Both of these versions are deprecated upstream and we are currently no longer
using them on any system.

### CODE REVIEW

**Comment by ramereth** [comment]
[osl-php: Remove support for php 5.3 and 7.0 #38](https://trello.com/c/5H06HkO3/2072-osl-php-remove-support-for-php-53-and-70-38)

**Review by detjensrobert — APPROVED** [review]
LGTM

Possibly unrelated, why does Centos 8 only have one php package test?

**Comment by ramereth** [comment]
> Possibly unrelated, why does Centos 8 only have one php package test?

Because IUS doesn't work on EL8 and we haven't figured out dnf streams yet to deal with the other versions.

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v5.5.0.  Have a nice day!

**Pull request merged**
