### PR TITLE
Added PHP 7.4 to ius archive versions

### PR DESCRIPTION
**Pull request by Justin-Fernbaugh**

### CODE REVIEW

**Comment by Justin-Fernbaugh** [comment]
> Currently the tests are failing due to
> 
> > "rspec ./spec/packages_spec.rb[1:3:4:1:5] # osl-php::packages on centos 7 using php 7.4 using packages with versioned prefixes is expected to create yum_repository "ius-archive"

Resolved with latest commits.

**Review by ramereth — CHANGES_REQUESTED** [review]
Please update the InSpec test:
```
     ×  YumRepo ius-archive is expected not to be enabled
```

**Comment by Justin-Fernbaugh** [comment]
> Please update the InSpec test:
> 
> ```
>      ×  YumRepo ius-archive is expected not to be enabled
> ```

Pushed changes to fix the test

**Review by ramereth — APPROVED** [review]
Minor bump

**Comment by Justin-Fernbaugh** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v6.4.0.  Have a nice day!

**Pull request merged**
