### PR TITLE
Proper C8 support w/ Remi modules

### PR DESCRIPTION
**Pull request by detjensrobert**
Adds proper support for installing different versions of PHP on CentOS 8.

This uses the Remi repo on CentOS 8, as it is simpler and IUS does not support C8 anyway.

Remi has packages for PHP 8.0 and 8.1, so this PR also adds support for those (C8 only -- IUS does not offer PHP8).

Also included is an Apache PHP site to verify that mod_php is working correctly across the suite of versions tested.

### CODE REVIEW

**Comment by ramereth** [comment]
Overall this LGTM but let's wait until the upstream PRs have been merged/released.

**Review by ramereth — APPROVED** [review]
Major bump

**Comment by detjensrobert** [comment]
!bump major ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v6.0.0.  Have a nice day!

**Pull request merged**
