### PR TITLE
Enable Selinux Enforcing

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Enable SELinux Enforcing](https://trello.com/c/WlALaNKE/930-enable-selinux-enforcing)

**Comment by ramereth** [comment]
@zimmerry looks like you're missing the selinux InSpec tests, can you please add them?

**Comment by zimmerry** [comment]
> @zimmerry looks like you're missing the selinux InSpec tests, can you please add them?

Oops, `git commit -am` missed those.

**Comment by ramereth** [comment]
@zimmerry with the amount of duplication you're doing in this PR, perhaps it might be a good idea to switch this cookbook over to using InSpec profile in a separate PR and then adjust this PR for that. How you feel about doing that? Me or @detjensrobert can help walk you through that process.

**Comment by detjensrobert** [comment]
`osl-mailrelay` is using inspec profiles, you can take a look at those to get a general sense of how they work and how suites can depend on each other.

**Comment by zimmerry** [comment]
Sounds good, I'll start working on that.

**Review by ramereth — APPROVED** [review]
Please do a minor bump on `~`

**Comment by ramereth** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v5.8.0.  Have a nice day!

**Pull request merged**
